@startuml

' Define interfaces for the Observer pattern
interface Observer {
}

interface Subject {
}

' Define concrete classes for the Observer pattern
class WaitStaffObserver implements Observer {
}

class KitchenStaffObserver implements Observer {
}

class OrderSubject implements Subject {
}

class OrderItemSubject implements Subject {
}

' Define interfaces and classes for the State pattern for MenuItems
interface ItemState {
}

class Queueing implements ItemState {
}

class Cooking implements ItemState {
}

class Cooked implements ItemState {
}

class Served implements ItemState {
}

class OrderItemContext {
}

class MenuItem {
}

' Define user roles
abstract User {
}

class KitchenStaff {
}

class WaitStaff {
}

class Manager {
}

class RegularUser {
}

' Link users to Observer roles
WaitStaffObserver -down-|> WaitStaff
KitchenStaffObserver -down-|> KitchenStaff

' Connect the menu items to the order and states
OrderItemContext -left-> ItemState
OrderItemContext -right-> OrderItemSubject
OrderItemContext --> OrderItem: contains
OrderItem --> MenuItem : include

Order --> OrderItem : contains

Order -right-> OrderSubject

' Link Subject to Observers explicitly
OrderSubject "1" -down-> "*" Observer : notifies >
OrderItemSubject "1" -right-> "*" Observer : notifies >

' Composite pattern relations for user
User <|-- WaitStaff
User <|-- KitchenStaff
User <|-- Manager
User <|-- RegularUser

' Define Singleton for Analytics
class Analytics {
}

Analytics <-down- Manager

class OrderFactory {
}

OrderFactory --> Order : Creates

' Link WaitStaff to creating OrderItem
WaitStaff --> OrderFactory : Uses

Order -> OrderItemContext : contains

interface OrderState {
}

class Reserving implements OrderState {
}

class Serving implements OrderState {
}

class Paying implements OrderState {
}

class Paid implements OrderState {
}

Order -> OrderState

@enduml
