@startuml

User *-- WaitStaff
User *-- KitchenStaff
User *-- Manager
User *-- RegularUser

Manager -down-> Analytic : use

RegularUser "1" -down-> "1..n" Order : create
Order "1" -- "1..n" Receipt : for

KitchenStaff "1" -down-> Order : update
WaitStaff "1" -down-> Order : update

Order "1" o-- "1..n" OrderItem : contains
Order "1" --> "1" OrderState: has
Order "1..n" ---> "1" Table: in

Reserving .up.|> OrderState
Serving .up.|> OrderState
Paying .up.|> OrderState
Paid .up.|> OrderState

OrderItem -left-> MenuItem
OrderItem "1" -- "1" OrderItemState : has


Queueing .up.|> OrderItemState
Cooking .up.|> OrderItemState
Cooked .up.|> OrderItemState
Served .up.|> OrderItemState

@enduml

